### ISSUE TITLE
jsp?

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/com_zimbra_converse#1]
@yuntux in your wordpress post you enable jsp's but there is no jsp in the sources of the project.

Can you release the jsp?

**Comment by yuntux** [comment]
Maybe you missed that file : https://github.com/Zimbra-Community/com_zimbra_converse/blob/master/com_zimbra_converse/get_cookie.jsp

**Comment by barrydegraaff** [comment]
sorry, was looking at github cache.

Thanks for your work!

**Comment by yuntux** [comment]
By the way, in Zimbra 8.8 the chat is integrated. So this extension will be useless very soon.

**Comment by barrydegraaff** [comment]
I know, its just there as an example of what one can do. 

I pulled it from zimbra.org. 

Kind regards, 

Barry de Graaff 
Zeta Alliance Founder 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 
Skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
